version: 2

models:
  - name: int_sales_orders_enriched
    description: "銷售訂單 enrich，包含金額幣別換算 (USD)"
    columns:
      - name: order_id
        description: "訂單編號"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "客戶編號"
      - name: order_date
        description: "訂單日期"
      - name: order_amount
        description: "原始訂單金額"
      - name: order_currency
        description: "原始幣別"
      - name: order_amount_usd
        description: "金額 (USD)"
