version: 2

sources:
  - name: raw
    description: "A source for raw data from our application database."
    database: raw_db # replace with your raw database
    schema: main
    tables:
      - name: customers
        description: "One record per customer."
      - name: orders
        description: "One record per order."
