version: 2

sources:
  - name: raw
    description: "原始 seed 資料來源（由 dbt seed 匯入）"
    schema: public
    tables:
      - name: raw_sales_orders
        description: "銷售訂單原始資料 (由 seeds/raw_sales_orders.csv 匯入)"
